### ISSUE TITLE
adding script to the begining of head will cause IE X-UA-Compatible meta tag do not take effect.

### ISSUE THREAD

**Issue by pylemon** [mlavin/django-responsive#9]
``` html
<head>
<script>`content of django-responsive.js`</script>
 <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" >
...
</head>
```

this will make IE ignore the declaration of the meta tag.

put the content befor </head> can solve this problem. but not perfect.

**Comment by pylemon** [comment]
http://blogs.msdn.com/b/ieinternals/archive/2011/07/18/optimal-html-head-ordering-to-avoid-parser-restarts-redownloads-and-improve-performance.aspx

**Comment by mlavin** [comment]
This is an interesting issue. This script is at the top of the `<head>` to force the redirect (if needed) before any other scripts/css are requested by the browser. The cookie should also be available to all the scripts below it. A couple points from this article make this tempting to wontfix:

> For that reason, it is a best-practice to specify any X-UA-Compatible value as a HTTP response header.

and 

> Internet Explorer 10 PPB2 introduced a new architecture where a versioning pre-scan occurs before the parsers begin their work; the X-UA-Compatible META tag must appear in the first 4kb of the markup or it will be ignored.

**Comment by pylemon** [comment]
Yes, you are right, I need to find another way to work this around. Thanks.

**Comment by mlavin** [comment]
Closing based on previous discussion.
